### ISSUE TITLE
cannot pass data attribute to tg:component when uses with wrapper on v0.4.2

### ISSUE THREAD

**Issue by pojiro** [oiax/tgweb#53]
I write the link as an `article` like following

```
---
[data]
href = "#!" # this for _wrapper.html
---

<tg:component
  name="icons/facebook"
  data-class="mx-auto h-full w-2" # this for component
></tg:component>
```

the _wrapper.html is like

```
<a href="${href}" type="button"><tg:content></tg:content></a>
```

tg:component is like

```
<svg class="${class}"><path>...</path></svg>
```

---

I confirmed that can pass data attribute to tg:component without article.

**Comment by kuroda** [comment]
Thanks for the bug report.

Actually, the ability to pass custom properties to components and segments via the `data-*` attributes was working fine.

However, I have made a spec change in `v0.4.0` so that custom properties are not embedded in the `class` attribute.
This was because I felt it was necessary to protect the `class` attribute since it could also be rewritten by the newly introduced `tg:class` attribute.

That does not seem to be necessary, though. So, in `v0.4.3`, I changed the specification so that `${...}` in the `class` attribute is expanded.

In addition to this, `v0.4.3` changed the attribute name prefix for passing custom properties to components and segments from `data-` to `tg:data-` for consistency. 

The names of all attributes that have special meaning in tgweb and will be stripped in the final generated HTML document should begin with `tg:`.

So, please bump `tgweb` to `v0.4.3` and rewrite your HTML fragment as follows.

```html
<tg:component
  name="icons/facebook"
  tg:data-class="mx-auto h-full w-2" # this for component
></tg:component>
```
