### ISSUE TITLE
It would be useful to track `mv` of images/files

### ISSUE THREAD

**Issue by pojiro** [oiax/tgweb#75]
Currently, tgweb 0.4.x, if we mv a file under the images directory, tgweb doesn't detect the change and reload.
It would be nice and useful to track `move` and `rename` of images/files.

**Comment by kuroda** [comment]
@pojiro 

I checked with `tgweb 0.5.1` and could not reproduce the issue you noted.

Specifically, after cd'ing into the `src/images directory` in the terminal, I renamed the image files using the `mv foo.png bar.png` command, and the changes were reflected in the `dist/images` directory and the browser was reloaded.

Please check the operation again with the latest version of tgweb.

However, the source code that may be related to this issue has not been changed since `0.4.x`, so the situation may not improve in your environment.

**Comment by pojiro** [comment]
@kuroda I'm sorry for not replying.
I have confirmed that this issue does not occur in the latest version 0.6.0. So I close this issue. Thanks!!
